image: gradle:jdk17

stages:
  - build
  - unitTest  # Define a test stage
  - integrationTest
  - docker

before_script:
  - cd StockSync

WarehouseServiceTest:
  stage: unitTest
  script:
    - ./gradlew test --tests WarehouseServiceTests

WarehouseControllerTest:
  stage: unitTest
  script:
    - ./gradlew test --tests WarehouseControllerTests

IntegrationTest:  
  stage: integrationTest
  script:
    - ./gradlew test --tests SearchPageIntegrationTests

build:
  stage: build
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - StockSync/build/libs/



docker:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker build . -t stocksync/stocksync
    - docker compose -f SqlDocker.yml -p stocksync up -d
