image: gradle:jdk17

stages:
  - deploy

before_script:
  - chmod +x ./build_and_deploy.sh

deploy:
  stage: deploy
  script:
    - ./build_and_deploy.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "your-test-branch"'
